name: Build Android APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install dependencies and buildozer
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-setuptools python3-wheel cython3 openjdk-11-jdk unzip git wget
        pip3 install --upgrade cython
        pip3 install --upgrade buildozer

    - name: Download and set up NDK r21e
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip -d $HOME/.buildozer/android/platform/
        echo "LEGACY_NDK=$HOME/.buildozer/android/platform/android-ndk-r21e" >> $GITHUB_ENV

    - name: Install android-gfortran
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-gfortran
        cd $HOME/.buildozer/android/platform/android-gfortran
        wget https://github.com/mzakharo/android-gfortran/releases/download/v1.0/gcc-arm-linux-x86_64.tar.bz2
        wget https://github.com/mzakharo/android-gfortran/releases/download/v1.0/gcc-arm64-linux-x86_64.tar.bz2
        tar -xjf gcc-arm-linux-x86_64.tar.bz2
        tar -xjf gcc-arm64-linux-x86_64.tar.bz2
        echo "$HOME/.buildozer/android/platform/android-gfortran/bin" >> $GITHUB_PATH

    - name: Trigger Buildozer to create SDK folder
      run: |
        ~/.local/bin/buildozer android debug || true

    - name: Install Android SDK cmdline-tools & build-tools
      run: |
        mkdir -p ~/.buildozer/android/platform/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d ~/.buildozer/android/platform/android-sdk/cmdline-tools
        mv ~/.buildozer/android/platform/android-sdk/cmdline-tools/cmdline-tools ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest
        export PATH=$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses
        sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk \
          "platform-tools" \
          "platforms;android-33" \
          "build-tools;33.0.2"

    - name: Build final APK
      env:
        ANDROID_SDK_ROOT: $HOME/.buildozer/android/platform/android-sdk
        LEGACY_NDK: $HOME/.buildozer/android/platform/android-ndk-r21e
        PATH: /usr/bin:$HOME/.local/bin:$HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH
      run: |
        ~/.local/bin/buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: brs-visualizer-apk
        path: bin/*.apk
